import { motion } from "framer-motion";
import { ArrowLeft, Shield, FileText, Sparkles, Scale, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";

interface TOSProps {
  onBack: () => void;
}

export function TOS({ onBack }: TOSProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="h-full flex flex-col"
    >
      {/* Header */}
      <div className="flex items-center gap-4 p-4 border-b border-border">
        <Button variant="ghost" size="icon" onClick={onBack}>
          <ArrowLeft className="w-5 h-5" />
        </Button>
        <div>
          <h1 className="text-xl font-bold flex items-center gap-2">
            <Scale className="w-5 h-5 text-primary" />
            Terms of Service
          </h1>
          <p className="text-xs text-muted-foreground">Last Updated: February 2026</p>
        </div>
      </div>

      {/* Content */}
      <ScrollArea className="flex-1 min-h-0">
        <div className="max-w-3xl mx-auto space-y-8 p-6 pb-12">
          
          {/* Introduction */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <FileText className="w-4 h-4 text-primary" />
              1. Acceptance of Terms
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              By downloading, installing, or using Mimic AI ("Software"), you agree to be bound by these 
              Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Software. 
              These Terms constitute a legally binding agreement between you and the Mimic AI developers.
            </p>
          </section>

          {/* AI Disclosure */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-primary" />
              2. AI-Generated Content Disclosure
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Mimic AI uses artificial intelligence to generate responses and synthesize voices. 
              You acknowledge that:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>All content generated by the AI is synthetic and may contain errors or inaccuracies</li>
              <li>AI-generated content should not be relied upon for critical decisions</li>
              <li>The Software does not constitute legal, medical, financial, or professional advice</li>
              <li>You are solely responsible for how you use AI-generated content</li>
            </ul>
          </section>

          {/* Local Processing */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">3. Local Processing Disclosure</h2>
            <div className="p-4 bg-green-500/10 border border-green-500/30 rounded-lg">
              <p className="text-sm text-green-400 font-semibold mb-2">
                ✅ This Application Runs Locally on Your Device
              </p>
              <p className="text-sm text-muted-foreground">
                Mimic AI does not operate servers or cloud infrastructure. We do not collect, store, 
                or process your voice data, conversations, or generated content. All processing occurs 
                locally on your computer. However, you are responsible for securing your local device 
                and any data stored on it.
              </p>
            </div>
          </section>

          {/* User Responsibility */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold flex items-center gap-2 text-destructive">
              <Shield className="w-4 h-4" />
              4. User Responsibility & Assumption of Risk
            </h2>
            <div className="p-4 bg-destructive/10 border border-destructive/30 rounded-lg">
              <p className="text-sm text-destructive font-semibold mb-2">
                You Are Solely Responsible for Your Use of This Software
              </p>
              <p className="text-sm text-muted-foreground">
                This Software is provided as a tool. You bear full legal and ethical responsibility 
                for how you use it. We do not monitor, police, or verify your usage.
              </p>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              By using Mimic AI, you acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li><strong>You are solely responsible</strong> for all content you create using the Software</li>
              <li><strong>You assume all risks</strong> associated with AI-generated content</li>
              <li><strong>You are solely liable</strong> for any harm, damages, or violations resulting from your use</li>
              <li><strong>This Software is provided "AS-IS"</strong> without warranties or guarantees</li>
              <li><strong>You will comply with all applicable laws</strong> in your jurisdiction</li>
            </ul>
          </section>

          {/* Synthetic Voice Creation */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <Check className="w-4 h-4 text-green-400" />
              5. Synthetic Voice Creation
            </h2>
            <div className="p-4 bg-green-500/10 border border-green-500/30 rounded-lg">
              <p className="text-sm text-green-400 font-semibold mb-2">
                Synthetic Voices Only - No Voice Cloning
              </p>
              <p className="text-sm text-muted-foreground">
                Mimic AI creates voices entirely through AI synthesis using adjustable parameters. 
                All voices are artificially generated and unique.
              </p>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              You may create synthetic voices by adjusting parameters such as:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>Pitch, speed, and tone characteristics</li>
              <li>Gender and age parameters</li>
              <li>Warmth, expressiveness, and stability settings</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-3">
              <strong className="text-destructive">Important:</strong> While voices are synthetically generated, 
              you may not use them to:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>Impersonate real individuals in a deceptive or fraudulent manner</li>
              <li>Create content intended to mislead others into believing a real person is speaking</li>
              <li>Engage in fraud, scams, or identity deception</li>
              <li>Harass, threaten, defame, or abuse any person</li>
              <li>Engage in political manipulation or influence operations</li>
              <li>Violate any applicable laws or regulations</li>
            </ul>
          </section>

          {/* AI Content Disclosure Obligations */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold flex items-center gap-2">
              <Shield className="w-4 h-4 text-primary" />
              6. AI Content Disclosure Obligations
            </h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              When sharing AI-generated audio or content publicly, you MUST:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>Clearly disclose that the content is AI-generated</li>
              <li>Not represent AI-generated content as human-created</li>
              <li>Not remove or attempt to remove AI watermarks</li>
              <li>Comply with all applicable platform policies and regulations regarding AI content</li>
            </ul>
          </section>

          {/* Watermarking */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">7. Audio Watermarking</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              All audio generated by this Software contains invisible watermarks identifying it as 
              AI-generated. This serves as forensic evidence of AI origin and cannot be removed. 
              You acknowledge that:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>Generated audio is automatically watermarked</li>
              <li>Watermarks persist through compression and common audio processing</li>
              <li>Attempting to remove watermarks violates these Terms</li>
              <li>Watermarked audio can be identified as AI-generated by detection tools</li>
            </ul>
          </section>

          {/* Data and Privacy */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">8. Data Processing and Privacy</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              Mimic AI is designed with privacy in mind:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>All voice parameters and configurations are stored locally on your device</li>
              <li>No voice recordings or personal data are transmitted to external servers</li>
              <li>Conversations are stored locally and are not accessible to developers</li>
              <li>You are responsible for securing your local data</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-3">
              For complete privacy information, please review our Privacy Policy.
            </p>
          </section>

          {/* Intellectual Property */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">9. Intellectual Property</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              <strong>Your Content:</strong> You retain rights to content you create, subject to compliance 
              with these Terms and respect for third-party rights.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              <strong>Generated Content:</strong> AI-generated output is provided "as-is." We make no 
              claims of originality or copyright in generated content.
            </p>
            <p className="text-sm text-muted-foreground leading-relaxed">
              <strong>Synthetic Voices:</strong> Voices created through AI synthesis are artificial and 
              unique. However, you may not claim ownership of the underlying AI technology or attempt to 
              restrict others from using similar parameter combinations.
            </p>
          </section>

          {/* Disclaimer of Warranties */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">10. Disclaimer of Warranties</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              THE SOFTWARE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR 
              PURPOSE, OR NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SOFTWARE WILL BE ERROR-FREE, 
              SECURE, OR AVAILABLE AT ALL TIMES.
            </p>
          </section>

          {/* Limitation of Liability */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">11. Limitation of Liability</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>We are not liable for any misuse of the Software by users</li>
              <li>We are not liable for content generated by users</li>
              <li>We are not liable for disputes arising from use of synthetic voices</li>
              <li>Total liability shall not exceed amounts paid for the Software (which is free)</li>
            </ul>
          </section>

          {/* Indemnification */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">12. Indemnification</h2>
            <div className="p-4 bg-destructive/10 border border-destructive/30 rounded-lg">
              <p className="text-sm text-destructive font-semibold mb-2">
                You Will Defend Us Against Claims Resulting From Your Use
              </p>
            </div>
            <p className="text-sm text-muted-foreground leading-relaxed">
              <strong>You agree to indemnify, defend, and hold harmless</strong> the developers, contributors, 
              and affiliates from and against any and all claims, damages, losses, liabilities, costs, 
              and expenses (including reasonable attorneys' fees) arising from or relating to:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>Your use of the Software</li>
              <li>Impersonation, fraud, or deceptive practices using the Software</li>
              <li>Distribution of undisclosed AI-generated content</li>
              <li>Violation of any third-party rights (privacy, publicity, intellectual property)</li>
              <li>Violation of any law, regulation, or these Terms</li>
              <li>Any content you create, distribute, or publish using the Software</li>
              <li>Any harm or damages resulting from your use of the Software</li>
            </ul>
            <p className="text-sm text-muted-foreground leading-relaxed mt-3">
              This indemnification obligation survives termination of these Terms.
            </p>
          </section>

          {/* Termination */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">13. Termination</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may terminate your license for violations of these Terms. Upon termination:
            </p>
            <ul className="list-disc list-inside text-sm text-muted-foreground space-y-1 ml-4">
              <li>You must cease all use of the Software</li>
              <li>You remain liable for actions taken while using the Software</li>
              <li>Local data remains on your device and is your responsibility to delete</li>
            </ul>
          </section>

          {/* Changes to Terms */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">14. Changes to Terms</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              We may update these Terms from time to time. We will notify users of significant changes 
              through the Software or via the project's communication channels. Continued use of the 
              Software after changes constitutes acceptance of the updated Terms.
            </p>
          </section>

          {/* Governing Law */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">15. Governing Law</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              These Terms are governed by the laws of your jurisdiction of residence, without regard 
              to conflict of law principles. Any disputes arising from these Terms shall be resolved 
              in the courts of that jurisdiction.
            </p>
          </section>

          {/* Contact */}
          <section className="space-y-3">
            <h2 className="text-lg font-semibold">16. Contact</h2>
            <p className="text-sm text-muted-foreground leading-relaxed">
              For legal inquiries, questions about these Terms, or to report violations, please contact 
              us through the project's official channels or GitHub repository.
            </p>
          </section>

          {/* Agreement */}
          <div className="pt-8 border-t border-border">
            <p className="text-sm text-center text-muted-foreground">
              BY USING MIMIC AI, YOU ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE 
              BOUND BY THESE TERMS OF SERVICE.
            </p>
          </div>

        </div>
      </ScrollArea>
    </motion.div>
  );
}

export default TOS;
